Feat/version2.0 feature merges
ArunaStorage/ArunaServer pull request #97
Opened 2023-07-31 12:31 UTC by lfbrehm

## Summary
This PR contains delete, relations and archive requests.
## Delete
- Resources are updated with `object_status = DELETED`
## Relations
- The API request `ModifyRelations` is now implemented
## Archive/Snapshot
- Projects and all resources belonging to the object are updated to `dynamic = false`
- Collections/Datasets are cloned with a persistent copy

2023-07-31 13:02 UTC, St4NNi requested changes
Good work, one thing i really do not like is iterating over DB requests. We should add get / update requests that take a list and process them all at once.

2023-07-31 13:02 UTC, St4NNi commented on src/database/dsls/internal_relation_dsl.rs
> +        let outbound = "SELECT * FROM internal_relations
not a fan, we should combine outbound and inbound to one request:

`SELECT * FROM internal_relations  WHERE target_pid = $1 OR origin_pid = $1;

And separate the afterwards, especially since you are iterating over them anyway.

`Iterator::partition` can be used to get two vectors.

2023-07-31 13:02 UTC, St4NNi commented on src/grpc/collections.rs
> +        for o in updates {
Not a fan either, would prefer updating them all at once, with one db request.

2023-07-31 13:02 UTC, St4NNi commented on src/grpc/collections.rs
> +        for resource in &resources {
Again, for loop for updating sounds not like a good idea.

2023-07-31 13:02 UTC, St4NNi commented on src/grpc/datasets.rs
> +        for o in updates {
Same as col.

2023-07-31 13:02 UTC, St4NNi commented on src/grpc/object.rs
> +        for o in updates {
Again updating them all separately is a bad idea

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/delete_db_handler.rs
> +                        Object::get_object_with_relations(&id, &transaction_client).await?;
Unnecessary borrow `&transaction_client`

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/delete_db_handler.rs
> +                        Object::set_deleted(&id, &transaction_client).await?
`&transaction_client` -> `transaction_client`

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/delete_db_handler.rs
> +                    Object::set_deleted(&id, &transaction_client).await?;
`&transaction_client` -> `transaction_client`

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/delete_db_handler.rs
> +                Object::set_deleted(&id, &transaction_client).await?;
`&transaction_client` -> `transaction_client`

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/delete_db_handler.rs
> +        for id in resources {
Same as others, for loop over database requests is a no-go

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/relations_db_handler.rs
> +        for internal_to_add in labels_to_add.internal {
For loops over DB requests

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/relations_db_handler.rs
> +        for external_to_remove in labels_to_remove.external {
... for...

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/relations_db_handler.rs
> +        for internal_to_remove in labels_to_remove.internal {
for...

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/snapshot_request_types.rs
> +        for relation in &project.relation_ids {
for ...

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/snapshot_request_types.rs
> +        for resource in &project.resource_ids {
for...

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/snapshot_request_types.rs
> +            result.push(Object::get_object_with_relations(resource, client).await?);
updating AND retrieving with two requests in a for loop is really bad

2023-07-31 13:02 UTC, St4NNi commented on src/middlelayer/snapshot_request_types.rs
> +            let (outs, ins) = InternalRelation::get_all_by_id(id, client).await?;
get_all in for loop ?

2023-07-31 13:23 UTC, das-Abroxas requested changes
Some copy & paste things that should be smoothed out before merge.

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/projects.rs
> +            tonic_internal!(project.try_into(), "Collection conversion error");
Copy & paste only partially adapted.

```suggestion
        let project_id = tonic_invalid!(request.get_id(), "Invalid project id");
        let ctx = Context::res_ctx(project_id, DbPermissionLevel::WRITE, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        let project = tonic_internal!(
            self.database_handler.update_name(request).await,
            "Internal database error."
        );
        self.cache
            .update_object(&project.object.id, project.clone());
        let project: generic_resource::Resource =
            tonic_internal!(project.try_into(), "Project conversion error");
```

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/projects.rs
> +            tonic_internal!(project.try_into(), "Collection conversion error");
Copy & paste only partially adapted.

```suggestion
        let request = DescriptionUpdate::Project(request.into_inner());
        let project_id = tonic_invalid!(request.get_id(), "Invalid project id");
        let ctx = Context::res_ctx(project_id, DbPermissionLevel::WRITE, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        let project = tonic_internal!(
            self.database_handler.update_description(request).await,
            "Internal database error."
        );
        self.cache
            .update_object(&project.object.id, project.clone());
        let project: generic_resource::Resource =
            tonic_internal!(project.try_into(), "Project conversion error");
```

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/projects.rs
> +            tonic_internal!(project.try_into(), "Collection conversion error");
Copy & paste only partially adapted.

```suggestion
        let project_id = tonic_invalid!(request.get_id(), "Invalid project id");
        let ctx = Context::res_ctx(project_id, DbPermissionLevel::WRITE, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        let project = tonic_internal!(
            self.database_handler.update_keyvals(request).await,
            "Internal database error."
        );
        self.cache
            .update_object(&project.object.id, project.clone());
        let project: generic_resource::Resource =
            tonic_internal!(project.try_into(), "Project conversion error");
```

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/projects.rs
> +            tonic_internal!(project.try_into(), "Collection conversion error");
Copy & paste only partially adapted.

```suggestion
        let project_id = tonic_invalid!(request.get_id(), "Invalid project id");
        let ctx = Context::res_ctx(project_id, DbPermissionLevel::WRITE, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        let project = tonic_internal!(
            self.database_handler.update_dataclass(request).await,
            "Internal database error."
        );
        self.cache
            .update_object(&project.object.id, project.clone());
        let project: generic_resource::Resource =
            tonic_internal!(project.try_into(), "Project conversion error");
```

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/projects.rs
> +            tonic_internal!(resources[0].clone().try_into(), "Dataset conversion error");
Copy & paste only partially adapted.

```suggestion
        let project_id = tonic_invalid!(request.get_id(), "Invalid project id");
        let ctx = Context::res_ctx(project_id, DbPermissionLevel::ADMIN, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        // This contains all the resources the snapshot includes below the project
        let resources = tonic_internal!(
            self.database_handler.snapshot(request).await,
            "Internal database error."
        );
        for resource in &resources {
            self.cache
                .update_object(&resource.object.id, resource.clone());
        }
        let project: generic_resource::Resource =
            // First entry is always the archived project 
            tonic_internal!(resources[0].clone().try_into(), "Project conversion error");
```

2023-07-31 13:23 UTC, das-Abroxas commented on src/grpc/collections.rs
> +            tonic_internal!(resources[0].clone().try_into(), "Dataset conversion error");
Copy & paste only partially adapted.

```suggestion
        let collection_id = tonic_invalid!(request.get_id(), "Invalid collection id.");
        let ctx = Context::res_ctx(collection_id, DbPermissionLevel::ADMIN, true);

        tonic_auth!(
            self.authorizer.check_permissions(&token, vec![ctx]).await,
            "Unauthorized"
        );

        // This contains all resources the snapshot includes below the collection
        let resources = tonic_internal!(
            self.database_handler.snapshot(request).await,
            "Internal database error."
        );
        for resource in &resources {
            self.cache
                .update_object(&resource.object.id, resource.clone());
        }
        let collection: generic_resource::Resource =
        // First entry is always the snapshot collection
            tonic_internal!(resources[0].clone().try_into(), "Collection conversion error");
```

2023-08-03 08:49 UTC, St4NNi approved these changes
Nice, additions for now LGTM. This will surely be modified in further developments.

2023-08-03 09:28 UTC, das-Abroxas approved these changes

2023-08-03 09:40 UTC, merged